### PR TITLE
Autoscaling register instance

### PR DESCRIPTION
**Pull request by shiimaxx**
Added new endpoint `/autoscale/instance/register`.
When do API request with parameter to this endpoint, happo-agent register instance data with dbms.

I thinking of using this endpoint when AutoScaling instance register self instance data after launch.

### CODE REVIEW

**Comment by shiimaxx** [comment]
Please review. @netmarkjp

**Comment by netmarkjp** [comment]
@shiimaxx Thanks. looks good :relaxed: 

I want to have one discussion about logging.
When do we should logging behaviors?

- `missing parameter` (in case misconfiguration?)
- endpoint returns 200

**Comment by shiimaxx** [comment]
@netmarkjp Thanks for review.

I think following  case should logging behaviors.

- logging for error message when request failed
    - It is contain `missing parameter`
- logging for registered information(alias, instance data) when endpoint returns 200

What do you think this?

**Comment by netmarkjp** [comment]
@shiimaxx I think that your proposal looks good :relaxed:

**Comment by shiimaxx** [comment]
I added logging for `model.AutoScalingInstanceRegister`.
If endpoint returns 200, loglevel is "info" else "warn".

```
2018-05-24 08:09:23 [warning] failed to register i-aaaaaa:missing parameter
2018-05-24 08:09:29 [warning] failed to register i-aaaaaa:can't find autoscaling group name in config
2018-05-24 08:09:37 [warning] failed to register i-aaaaaa:already registered
2018-05-24 08:09:42 [info] register i-bbbbbb with alias hb-autoscaling-hb-app-4
```

**Comment by netmarkjp** [comment]
Thanks. looks good to me :relaxed:

**Pull request merged**
