### PR TITLE
add feature of storing autoscaling info

### PR DESCRIPTION
**Pull request by shiimaxx**
This patch is implement storing autoscaling info with dbms.

add endpoints.

- `GET /autoscaling`
    - list autoscaling instances
- `POST /autoscaling/config/update`
    - save autoscaling config
- `POST /autoscaling/refresh`
    - refresh registered instances in dbms

### CODE REVIEW

**Comment by netmarkjp** [comment]
Thaks!
I have few questions and requests. 

- I hope you to write to README.md about new endpoints
- In case plural AutoScalingGroup has same hostname, DB key might conflict isn't it?
    - DB key should contain AutoScalingGroupName(raw or base64 encoded)?
- `autoscaling.AutoScalingRefresh` : In the case `request.AutoScalingGroupName == ""` , now return error. Which is better that, return error or refresh all AutoScalingGroup?
- `autoscaling.AutoScalingRefresh` : In the case AutoScalingGroupName is not contain in Config, return error properly?
- When some AutoScalingGroup removed from autoscaling.yaml (but still exists in AWS), how should we remove data in DB?
- In the case actual instances are more than `AutoScalingConfig.AutoScalings[].AutoScalingCount`, overflow instances are simply ignored isn't it?

**Comment by shiimaxx** [comment]
Thanks for review.

> - I hope you to write to README.md about new endpoints

Sorry I forgot update README.md, I updated README.md, README.ja.md in 0975bb6 and 7004634.

> - In case plural AutoScalingGroup has same hostname, DB key might conflict isn't it?
>     - DB key should contain AutoScalingGroupName(raw or base64 encoded)?

It sure is, possibility of DB key conflict.
I accepted your proposal, and fixed it in edff744.

> - autoscaling.AutoScalingRefresh : In the case request.AutoScalingGroupName == "" , now return error. Which is better that, return error or refresh all AutoScalingGroup?

I think better refresh all AutoScalingGroup, because currently not provide way to be that.
I fixed in 266d3e9, what do you think about this code?

> - autoscaling.AutoScalingRefresh : In the case AutoScalingGroupName is not contain in Config, return error properly?

In that case return error, but that error is validation error in autoscaling.RefreshAutoScalingInstances, I think inappropriate it.
For that reason I fixed in 49a932b.

> - When some AutoScalingGroup removed from autoscaling.yaml (but still exists in AWS), how should we remove data in DB?

Currently no way to be remove, but I will implement some remove api after this PR.

> - In the case actual instances are more than AutoScalingConfig.AutoScalings[].AutoScalingCount, overflow instances are simply ignored isn't it?

Yes. even if instances is scale out and execute `/autoscaling/refresh` api, stay remain already registered instances.

**Comment by netmarkjp** [comment]
Thanks a lot. Almost looks good :relaxed: 

> > - In case plural AutoScalingGroup has same hostname, DB key might conflict isn't it?
> >     - DB key should contain AutoScalingGroupName(raw or base64 encoded)?
> 
> It sure is, possibility of DB key conflict.
> I accepted your proposal, and fixed it in edff744.

In the case both `GroupName: sysx-web-a, HostPrefix: ap` and `GroupName: sysx-web, HostPrefix: a-ap` are in same autoscaling.yaml, DB key will may be conflict.
I think this is very rare case, so I think we should take care about this case with documentation.
What do you think?

> > autoscaling.AutoScalingRefresh : In the case request.AutoScalingGroupName == "" , now return error. Which is better that, return error or refresh all AutoScalingGroup?
> 
> I think better refresh all AutoScalingGroup, because currently not provide way to be that.
> I fixed in 266d3e9, what do you think about this code?

It looks that works fine, but I think the code like below is much simple(natural) to me.

https://github.com/heartbeatsjp/happo-agent/blob/266d3e9632bf7ed3376262a3300496c93cb63078/model/autoscaling.go#L61-L82

```go
if matched || empty {
	...
}
if matched {
	break
}
```

**Comment by shiimaxx** [comment]
Thanks!

> In the case both GroupName: sysx-web-a, HostPrefix: ap and GroupName: sysx-web, HostPrefix: a-ap are in same autoscaling.yaml, DB key will may be conflict.
> I think this is very rare case, so I think we should take care about this case with documentation.
> What do you think?

I think so too, should take care about it.
I Updated README add description of autoscaling configuration contain it.

> It looks that works fine, but I think the code like below is much simple(natural) to me.

Thanks for advice. I improved this code for simplicity.

**Comment by netmarkjp** [comment]
Thanks! looks good to me.

**Pull request merged**
