### PR TITLE
Handle 404 in removing host

### PR DESCRIPTION
**Pull request by l3msh0**
This PR make the program output proper message when client management server returns `404 Not Found` as a response to `/manage/remove` .

### CODE REVIEW

**Comment by netmarkjp** [comment]
@l3msh0 Thanks a lot :relaxed: 

Almost looks good, but both "Not Found" and "Failed" will get same exit code, is this caused confusing?

**Comment by l3msh0** [comment]
@netmarkjp Thank you for reviewing.

I understand what you pointed out, but there seems not to be definite rules about exit code in this project.  Almost all existing unsuccessful case exits with the code `1` (e.g. [`CmdIsAdded` exits with code `1` when the host not found](https://github.com/heartbeatsjp/happo-agent/blob/c0d58d1c767d8589a53b4c86f183331320a09221/command/is_added.go#L30)) so I wonder giving special code to the case when host not found is outside the scope of this PR.

**Comment by netmarkjp** [comment]
@l3msh0 Thanks for reply.

As you say, we don't have definite rule.
In your use case, find result "Failed" or "Not Found" by output text is convenient ?
Or exit code is much better ?

Anyway, I merge this PR. Thanks.

**Comment by l3msh0** [comment]
@netmarkjp Thanks :pray:

> In your use case, find result "Failed" or "Not Found" by output text is convenient ?
Or exit code is much better ?

I think output text is enough in this case.

Assigning unique exit codes to various situations is complicating and `/manage/remove` is not intended to check if a host is registered. In my opinion,  users should call `/manage/is_added` instead if they really want to check the host's existence.

**Pull request merged**
