### PR TITLE
Alias of auto scaling instances are changed to suffix is zero padding

### PR DESCRIPTION
**Pull request by shiimaxx**
before:
- dummy-prod-ag-dummy-prod-app-1
- dummy-prod-ag-dummy-prod-app-2
- ...

after:
- dummy-prod-ag-dummy-prod-app-01
- dummy-prod-ag-dummy-prod-app-02
- ...

@netmarkjp 
Please review.

### CODE REVIEW

**Comment by netmarkjp** [comment]
note: I retrying daemontest ...

**Comment by netmarkjp** [comment]
@shiimaxx Thanks!

I retried daemontest, but failed.
As that result, CPU Usage is about 6%. The result past version is under 4% (4% is threshold).

Do you have any idea of the reason, why CPU Usage become high?

(now I still retrying daemontest ...)

**Comment by shiimaxx** [comment]
@netmarkjp 

I think cause of fail of daemontest is code change by https://github.com/heartbeatsjp/happo-agent/pull/37.
(Saw history of daemontest, confirmed not executed at above PR merge)

**Comment by netmarkjp** [comment]
@shiimaxx As you say, this PR may not be the cause of increase CPU Usage.
So I merge this PR, and let's find the true cause at another PR.

**Pull request merged**
